[env:esp32s2]
platform = espressif32
board = lolin_s2_mini
framework = arduino
monitor_speed = 115200

board_build.partitions = partitions/custom.csv
board_upload.flash_size = 4MB
board_build.cmake_extra_args = -DSDKCONFIG_DEFAULTS="sdkconfig.defaults"

lib_deps =
    ESP32Async/ESPAsyncWebServer@^3.0.0
    ESP32Async/AsyncTCP@^3.0.0
    bblanchon/ArduinoJson@^7.0.0

build_flags =
    -DARDUINO_USB_MODE=0
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DBOARD_HAS_PSRAM
    -O2