// generated by export_model.py - do not edit by hand
#pragma once

#define NUM_WEIGHT_LAYERS 28
#define MODEL_LATENT_DIM 32
#define MODEL_EMB_DIM 16
#define MODEL_COND_DIM 48
#define MODEL_NUM_CLASSES 10
#define MODEL_NUM_COLORS 24
#define MODEL_IMG_SIZE 32
#define MODEL_C1 64
#define MODEL_C2 128
#define MODEL_C3 192

// order of tensors inside model_weights.bin:
// [ 0] class_embed_weight
// [ 1] emb_proj_weight
// [ 2] emb_proj_bias
// [ 3] projection_weight
// [ 4] projection_bias
// [ 5] up1_conv_weight
// [ 6] up1_conv_bias
// [ 7] up1_gn_weight
// [ 8] up1_gn_bias
// [ 9] film1_weight
// [10] film1_bias
// [11] up2_conv_weight
// [12] up2_conv_bias
// [13] up2_gn_weight
// [14] up2_gn_bias
// [15] film2_weight
// [16] film2_bias
// [17] up3_conv_weight
// [18] up3_conv_bias
// [19] up3_gn_weight
// [20] up3_gn_bias
// [21] film3_weight
// [22] film3_bias
// [23] refine_weight
// [24] refine_bias
// [25] classifier_weight
// [26] classifier_bias
// [27] class_latents

static const char* CLASS_NAMES[] = {
    "T-shirt",
    "Trouser",
    "Pullover",
    "Dress",
    "Coat",
    "Sandal",
    "Shirt",
    "Sneaker",
    "Bag",
    "Ankle boot",
};
